categories:
  electronics:
    reviews_url: "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFiles/Electronics.json.gz"
    meta_url: "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/metaFiles2/meta_Electronics.json.gz"
  home_kitchen:
    reviews_url: "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFiles/Home_and_Kitchen.json.gz"
    meta_url: "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/metaFiles2/meta_Home_and_Kitchen.json.gz"
  dev:
    reviews_url: "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFiles/All_Beauty.json.gz"
    meta_url: "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/metaFiles2/meta_All_Beauty.json.gz"