USE ROLE TRAINING_ROLE;

-- Warehouse
CREATE OR REPLACE WAREHOUSE SIGNALFLOWAI_ETL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + Schemas
CREATE OR REPLACE DATABASE SIGNALFLOWAI_DB;

CREATE OR REPLACE SCHEMA SIGNALFLOWAI_DB.RAW;
CREATE OR REPLACE SCHEMA SIGNALFLOWAI_DB.CLEAN;
CREATE OR REPLACE SCHEMA SIGNALFLOWAI_DB.CURATED;

-- Context
USE WAREHOUSE SIGNALFLOWAI_ETL_WH;
USE DATABASE SIGNALFLOWAI_DB;
USE SCHEMA RAW;

-- Parquet file format (for landing/parquet files)
CREATE OR REPLACE FILE FORMAT PARQUET_FF
  TYPE = PARQUET;


-- Verify
USE ROLE TRAINING_ROLE;
SHOW WAREHOUSES LIKE 'SIGNALFLOWAI_ETL_WH';
SHOW SCHEMAS IN DATABASE SIGNALFLOWAI_DB;
SHOW FILE FORMATS IN SCHEMA SIGNALFLOWAI_DB.RAW;