USE ROLE TRAINING_ROLE;

CREATE OR REPLACE STORAGE INTEGRATION SIGNALFLOWAI_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::904233093023:role/signalflowai-snowflake-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://signalflowai-s3/landing/parquet/');


-- verify
DESC INTEGRATION SIGNALFLOWAI_S3_INT;