USE ROLE TRAINING_ROLE;
USE WAREHOUSE SIGNALFLOWAI_ETL_WH;
USE DATABASE SIGNALFLOWAI_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE SIGNALFLOWAI_DB.RAW.S3_LANDING_STAGE
  URL = 's3://signalflowai-s3/landing/parquet/'
  STORAGE_INTEGRATION = SIGNALFLOWAI_S3_INT
  FILE_FORMAT = SIGNALFLOWAI_DB.RAW.PARQUET_FF;


-- verify
DESC INTEGRATION SIGNALFLOWAI_S3_INT;

LIST @SIGNALFLOWAI_DB.RAW.S3_LANDING_STAGE/reviews/;
LIST @SIGNALFLOWAI_DB.RAW.S3_LANDING_STAGE/meta/;