USE ROLE TRAINING_ROLE;

-- Warehouse (assumes it already exists; optional)
USE WAREHOUSE SIGNALFLOWAI_ETL_WH;

-- PROD Database + Schemas
CREATE DATABASE IF NOT EXISTS SIGNALFLOWAI_PROD_DB;

CREATE SCHEMA IF NOT EXISTS SIGNALFLOWAI_PROD_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SIGNALFLOWAI_PROD_DB.CLEAN;
CREATE SCHEMA IF NOT EXISTS SIGNALFLOWAI_PROD_DB.CURATED;

-- Context
USE DATABASE SIGNALFLOWAI_PROD_DB;
USE SCHEMA RAW;

-- File format (Parquet)
CREATE FILE FORMAT IF NOT EXISTS PARQUET_FF
  TYPE = PARQUET;

-- External stage (reuses existing storage integration)
CREATE STAGE IF NOT EXISTS S3_LANDING_STAGE
  URL = 's3://signalflowai-s3/landing/parquet/'
  STORAGE_INTEGRATION = SIGNALFLOWAI_S3_INT
  FILE_FORMAT = PARQUET_FF;

-- Quick verification
SHOW SCHEMAS IN DATABASE SIGNALFLOWAI_PROD_DB;
SHOW FILE FORMATS IN SCHEMA SIGNALFLOWAI_PROD_DB.RAW;
LIST @S3_LANDING_STAGE/reviews/;
LIST @S3_LANDING_STAGE/meta/;