USE ROLE TRAINING_ROLE;
USE WAREHOUSE SIGNALFLOWAI_ETL_WH;
USE DATABASE SIGNALFLOWAI_PROD_DB;
USE SCHEMA RAW;


--
SELECT 'RAW.REVIEWS_RAW' AS table_name, COUNT(*) AS cnt FROM SIGNALFLOWAI_PROD_DB.RAW.REVIEWS_RAW
UNION ALL
SELECT 'CLEAN.CLEAN_REVIEWS', COUNT(*) FROM SIGNALFLOWAI_PROD_DB.CLEAN.CLEAN_REVIEWS
UNION ALL
SELECT 'CURATED.REVIEW_ENRICHED', COUNT(*) FROM SIGNALFLOWAI_PROD_DB.CURATED.REVIEW_ENRICHED
UNION ALL
SELECT 'RAW.META_RAW', COUNT(*) FROM SIGNALFLOWAI_PROD_DB.RAW.META_RAW
UNION ALL
SELECT 'CLEAN.CLEAN_META', COUNT(*) FROM SIGNALFLOWAI_PROD_DB.CLEAN.CLEAN_META
UNION ALL
SELECT 'CURATED.PRODUCT_HEALTH_DAILY', COUNT(*) FROM SIGNALFLOWAI_PROD_DB.CURATED.PRODUCT_HEALTH_DAILY;

-- meta coverage
SELECT
  COUNT(*) AS total_reviews,
  COUNT_IF(title IS NOT NULL) AS reviews_with_title,
  ROUND(COUNT_IF(title IS NOT NULL) / NULLIF(COUNT(*), 0), 4) AS pct_with_meta
FROM SIGNALFLOWAI_PROD_DB.CURATED.REVIEW_ENRICHED;

-- meta dedupe
SELECT
  COUNT(*) AS meta_rows,
  COUNT(DISTINCT asin) AS distinct_asins
FROM SIGNALFLOWAI_PROD_DB.CLEAN.CLEAN_META;

-- coverage by category
SELECT
  category,
  COUNT(*) AS reviews,
  ROUND(COUNT_IF(title IS NOT NULL)/NULLIF(COUNT(*),0), 4) AS pct_with_meta
FROM SIGNALFLOWAI_PROD_DB.CURATED.REVIEW_ENRICHED
GROUP BY 1
ORDER BY reviews DESC;

SELECT COUNT(*) AS bad_rows
FROM SIGNALFLOWAI_PROD_DB.CURATED.PRODUCT_HEALTH_DAILY
WHERE positive_rate < 0 OR positive_rate > 1
   OR negative_rate < 0 OR negative_rate > 1;