name: 'signalflowai_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'signalflowai_dbt'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models

models:
  signalflowai_dbt:
    clean:
      +schema: CLEAN
      +materialized: table
    curated:
      +schema: CURATED
      +materialized: table
    rag:
      +schema: RAG
      +materialized: table

